public: false
type: "docs"
category: "collection development and management"
tags:
  - "tranfer"
  - "appraise"
  - "accession"
title: "Aurora"
description: "User documentation for the Aurora digital records transfer application"
pages:
  - ["Overview", "index"]
  - ["Features", "features"]
