version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - auroradb:/var/lib/mysql
  ldap:
    build: ldap/
    volumes:
      - .:/code
    ports:
      - "389:389"
    volumes:
      - auroraldap:/var/lib/ldap
  web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
      - ./aurora/:/data/htdocs/aurora/aurora/
      - storage:/data1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ldap

volumes:
  auroradb:
  auroraldap:
  storage:
